name = "techpulse"
pages_build_output_dir = "public"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "techpulse-db"
database_id = "bfce16c7-ce83-4c92-bff4-b9d4324061e0"

[ai]
binding = "AI"
